import { Service } from '@/types';

export const SERVICES: Service[] = [
  {
    id: 'classic-mani',
    name: 'Classic Manicure',
    category: 'basic',
    description: 'Essential nail care with shaping, cuticle treatment, and nail polish',
    duration: 45,
    price: 499,
    image: 'https://images.unsplash.com/photo-1610992015762-45dca7464f11?w=800&h=600&fit=crop&q=80',
    popular: true,
  },
  {
    id: 'classic-pedi',
    name: 'Classic Pedicure',
    category: 'basic',
    description: 'Relaxing foot soak, gentle scrubbing, massage, and nail polish',
    duration: 60,
    price: 699,
    image: 'https://images.unsplash.com/photo-1629198735700-610c0e49aab2?w=800&h=600&fit=crop&q=80',
    popular: true,
  },
  {
    id: 'gel-mani',
    name: 'Gel Manicure',
    category: 'premium',
    description: 'Long-lasting shiny gel polish dried under UV lamp, stays for 3 weeks',
    duration: 60,
    price: 899,
    image: 'https://images.unsplash.com/photo-1632345031435-8727f6897d53?w=800&h=600&fit=crop&q=80',
    popular: true,
  },
  {
    id: 'gel-pedi',
    name: 'Gel Pedicure Deluxe',
    category: 'premium',
    description: 'Special foot spa treatment with chip-free gel polish',
    duration: 75,
    price: 1099,
    image: 'https://images.unsplash.com/photo-1604654894610-df63bc536371?w=800&h=600&fit=crop&q=80',
  },
  {
    id: 'french-mani',
    name: 'French Manicure & Tips',
    category: 'premium',
    description: 'Classic clean style with natural pink base and white tips',
    duration: 50,
    price: 799,
    image: 'https://images.unsplash.com/photo-1606789674925-58a94bf6d1e8?w=800&h=600&fit=crop&q=80',
  },
  {
    id: 'nail-art-simple',
    name: 'Accent Nail Art (2-4 Nails)',
    category: 'art',
    description: 'Custom hand designs, glitter powder, or stones on special nails',
    duration: 60,
    price: 649,
    image: 'https://images.unsplash.com/photo-1610992015732-2449b76344bc?w=800&h=600&fit=crop&q=80',
  },
  {
    id: 'nail-art-complex',
    name: 'Full Set 3D Nail Art & Extensions',
    category: 'art',
    description: 'Full acrylic or gel extensions with 3D art, pearls, and diamonds',
    duration: 120,
    price: 1599,
    image: 'https://images.unsplash.com/photo-1604654894623-b5e7c0a5a6d1?w=800&h=600&fit=crop&q=80',
    popular: true,
  },
  {
    id: 'bridal-basic',
    name: 'Bridal Nail Package',
    category: 'bridal',
    description: 'Complete wedding care - gel manicure, pedicure, and bridal nail art',
    duration: 150,
    price: 2499,
    image: 'https://images.unsplash.com/photo-1519415510236-718bdfcd89c8?w=800&h=600&fit=crop&q=80',
  },
  {
    id: 'bridal-premium',
    name: 'Complete Bridal Glow Package',
    category: 'bridal',
    description: 'Full bridal gel extensions, custom art, luxury pedicure, and hand spa',
    duration: 240,
    price: 4999,
    image: 'https://images.unsplash.com/photo-1522673607910-e2ea5c749945?w=800&h=600&fit=crop&q=80',
    popular: true,
  },
];

export const CATEGORIES = [
  { id: 'all', label: 'All Services', value: 'all' },
  { id: 'basic', label: 'Basic Care', value: 'basic' },
  { id: 'premium', label: 'Gel & Extensions', value: 'premium' },
  { id: 'art', label: 'Nail Art', value: 'art' },
  { id: 'bridal', label: 'Bridal Packages', value: 'bridal' },
];
